config/routes.rb
Rails.application.routes.draw do
  get 'events/new'
  get 'sessions/new'
  get 'articles/new'
  get 'users/profil'
  get 'welcome/index'
  root 'welcome#index'
  resources :users

  get '/login' =>'sessions#new'

  post '/login' =>'sessions#create'
  # post '/login' =>'sessions#save'
  get '/logout' =>'sessions#destroy'
  get '/signup' =>'users#new'
  post '/users'=>'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
# attr_accessor :image
mount_uploader :file, FileUploader
before_save { self.email = email.downcase}
validates :name, presence: true
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, 
			format: {with: VALID_EMAIL_REGEX},
			uniqueness: {case_sensitive: false}
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	protect_from_forgery with: :exception

	def current_user
		@current_user ||= User.find(session[:user_id])if session[:user_id]
	end
	helper_method :current_user

	def authorize
		redirect_to 'login' unless current_user
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def new
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # before_action :authorize
  
  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
  	user = User.find_by_email(params[:email])

  	if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/event/new'
    else
     	redirect_to '/welcome/index'
    end
  end
#   def save
#     user = User.find_by_email(params[:email])

#     if user && user.authenticate(params[:password])
# session[:user_id] = user.id
# redirect_to '/articles/new'
# else
#   redirect_to '/welcome/index'
#     end
#   end 
  def destroy
  	session[:user_id] = nil
  	redirect_to '/welcome/index'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

  	def create
		user = User.new(user_params)
		if user.save
			session[:user_id] = user.id
			redirect_to '/events/new'
		else
			redirect_to '/signup'
		end
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			redirect_to '/users/profil'
		else
			render 'edit'
		end
	end

private
	def user_params
		params.require(:user).permit(:name,:email, :password, :password_confirmation, :file, :instansi, :minat, :level)		
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
<%if current_user%>
<div class="navbar navbar-expand-lg navbar-dark" style="background-color: #cc0000">
  <div class="navbar-brand" id="bor"><%= image_tag("logo.png", width:"80px")%></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContent" align="center">
  <ul class="navbar-nav mr-auto">
    
    <li class="nav-item">
          <a id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%=link_to 'Events', '/events/new', class: 'nav-link'%>
        </a>
    </li>
    <li class="nav-item active">
          <a class="nav-link" href="#" id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
    </li>
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item ">
      
      </li>
    <li class="nav-item">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag current_user.file_url,class: 'img-circle1' %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item"><center><%=current_user.name%></center></a>
          <div class="dropdown-divider"></div>
          <center><%=link_to 'Profil', '/users/profil' , class: 'dropdown-item'%></center>
          <center><%=link_to "Logout",'/logout' ,class: 'dropdown-item'%></center>
        </div>
      </li>
    </li>
  </ul>
</div>
</div>

<div class="row">
<div class="col-md-12">
		<div class="card" id="jar">
			<div class="card-header" align="center" style="height: 50px"><h2 class="pro">Events</h2></div>
				<div class="card-body bg-secondary" style="height: 450px">
	  			<%=current_user.name%>	
	  			</div>
		</div>

</div>

</div>
<div class="bottom">
<div class="navbar navbar-expand-lg navbar-dark" style="background-color: #cc0000">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContentfoot" aria-controls="navbarSupportedContentfoot" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContentfoot" align="center">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="#">About Us<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">How To Join<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">Term & Conditions<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">Privacy Policy<span class="sr-only">(current)</span></a>
    </li>
  </ul>
</div>
</div>
</div>
      <%else%>
      Anda Tidak Memiliki Akun <%= link_to 'Index' , '/welcome/index'%>
      <%end%>

app/views/events/new.html.erb
<%if current_user%>
<div class="navbar navbar-expand-lg navbar-dark" style="background-color: #cc0000">
  <div class="navbar-brand" id="bor"><%= image_tag("logo.png", width:"80px")%></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContent" align="center">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
          <a id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%=link_to 'Events', 'new', class: 'nav-link'%>
        </a>
    </li>
    <li class="nav-item">
          <a href="#" id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= link_to 'Articles', '/articles/new',class: 'nav-link'%>
        </a>
    </li>
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item ">
      
      </li>
    <li class="nav-item">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag current_user.file_url,class: 'img-circle1' %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item"><center><%=current_user.name%></center></a>
          <div class="dropdown-divider"></div>
          <center><%=link_to 'Profil', '/users/profil' , class: 'dropdown-item'%></center>
          <center><%=link_to "Logout",'/logout' ,class: 'dropdown-item'%></center>
        </div>
      </li>
    </li>
  </ul>
</div>
</div>

<div class="row">
<div class="col-md-12">
    <div class="card" id="jar">
      <div class="card-header" align="center" style="height: 50px"><h2 class="pro">Events</h2></div>
        <div class="card-body bg-secondary" style="height: 450px">
          <%=current_user.name%>  
          </div>
    </div>

</div>

</div>
<div class="bottom">
<div class="navbar navbar-expand-lg navbar-dark" style="background-color: #cc0000">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContentfoot" aria-controls="navbarSupportedContentfoot" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContentfoot" align="center">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="#">About Us<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">How To Join<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">Term & Conditions<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">Privacy Policy<span class="sr-only">(current)</span></a>
    </li>
  </ul>
</div>
</div>
</div>
      <%else%>
      Anda Tidak Memiliki Akun <%= link_to 'Index' , '/welcome/index'%>
      <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/edit.html.erb
<%if current_user.level == '0'%>
<%=form_with model: @user, local: true do |form|%>
<div align="left">Full Name</div>
<div class="form-group">
<%=form.text_field :name, class: 'form-control'%>
</div>
<div align="left">Email</div>
<div class="form-group">
<%=form.text_field :email, class: 'form-control'%>
</div>
<div align="left">Instansi</div>
<div class="form-group">
<%= form.text_field :instansi, class: 'form-control'%>
</div>
<div align="left">Minat</div>
<div class="form-group">
<%=form.select :minat, options_for_select([["Product Manager","Product Manager"],[" Quality Assurance"," Quality Assurance"],["Design UI/UX","UI/UX"],["Web Develop","Web Develop"],["Mobile Develop","Mobile Develop"]]), class: 'form-control'%>
</div>
<div align="left">Level</div>
<div class="form-group">
	<%=form.select :level, options_for_select([["Admin","0"],["User","1"]]) , class: 'form-control'%>
</div>
<div align="left">Image</div>
<div class="form-group">
<%=form.file_field :image%>
</div>
<div align="right">
<%=form.submit%>
</div>
<%end%>
<%else%>
<%=form_with model: @user, local: true do |form|%>
<div align="left">Full Name</div>
<div class="form-group">
<%=form.text_field :name, class: 'form-control'%>
</div>
<div align="left">Instansi</div>
<div class="form-group">
<%= form.text_field :instansi, class: 'form-control'%>
</div>
<div align="left">Minat</div>
<div class="form-group">
<%=form.select :minat, options_for_select([["Product Manager","Product Manager"],[" Quality Assurance"," Quality Assurance"],["Design UI/UX","UI/UX"],["Web Develop","Web Develop"],["Mobile Develop","Mobile Develop"]]), class: 'form-control'%>
</div>
<div align="left">Image</div>
<div class="form-group">
<%=form.file_field :image%>
</div>
<div align="right">
<%=form.submit%>
</div>
<%end%>
<%end%>

app/views/users/new.html.erb
<%=form_with model: @user, local: true do |form|%>
<div align="left">Full Name</div>
<div class="form-group">
<%=form.label :name, class: 'form-control'%>
</div>
<div align="left">Email</div>
<div class="form-group">
<%=form.text_field :email, class: 'form-control'%>
</div>
<div align="left">Password</div> 
<div class="form-group">
<%=form.password_field :password, class: 'form-control'%>
</div>
<div align="left">Instansi</div>
<div class="form-group">
<%= form.text_field :instansi, class: 'form-control'%>
</div>
<div align="left">Minat</div>
<div class="form-group">
<%=form.text_field :minat, class: 'form-control'%>
</div>
<div align="left">Image</div>
<div class="form-group">
<%=form.file_field :image%>
</div>
<div align="right">
<%=form.submit%>
</div>
<%end%>

app/views/users/profil.html.erb
<%if current_user%>
<div class="navbar navbar-expand-lg navbar-dark" style="background-color: #cc0000">
  <div class="navbar-brand" id="bor"><%= image_tag("logo.png", width:"80px")%></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContent" align="center">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item ">
          <a id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%=link_to 'Events', '/events/new', class: 'nav-link'%>
        </a>
    </li>
    <li class="nav-item">
          <a href="#" id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= link_to 'Articles', '/articles/new',class: 'nav-link'%>
        </a>
    </li>
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item ">
      
      </li>
    <li class="nav-item">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag current_user.file_url,class: 'img-circle1' %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item"><center><%=current_user.name%></center></a>
          <div class="dropdown-divider"></div>
          <center><%=link_to 'Profil', '/users/profil' , class: 'dropdown-item'%></center>
          <center><%=link_to "Logout",'/logout' ,class: 'dropdown-item'%></center>
        </div>
      </li>
    </li>
  </ul>
</div>
</div>

<div class="row">
<div class="col-md-12">
		<div class="card" id="jar">
			<div class="card-header" align="center" style="height: 50px"><h2 class="pro">Profil Saya</h2></div>
				<div class="card-body bg-secondary" style="height: 450px">
          <form>
            <div class="row">
              <div class="col-md-2">
            Fullname<br>
	  				Email<br>
            Instansi<br>
            Minat<br>
            Level<br>
            <%=link_to 'EDIT', edit_user_path(current_user)%>
             </div>
             <%=current_user.name%> <br>
             <%=current_user.email%><br>
             <%=current_user.instansi%><br>
             <%=current_user.minat%><br>
             <%if current_user.level == '0'%>
             <%='Admin'%>
             <%else%>
             <%='User'%>
             <%end%>
             
             <br>
             <div class="col-md-2">
                <%= image_tag current_user.file_url, width: '100px', class: 'img-circle' %>
              </div>
            </div>
	  			</form>
          </div>
		</div>

</div>

</div>

      <%else%>
      Anda Tidak Memiliki Akun <%= link_to 'Index' , '/welcome/index'%>
      <%end%>

app/views/users/show.html.erb
<%=@user.name%>
<%=@user.email%>
<%@user.instansi%>
<%@user.minat%>
<%=link_to 'Edit', edit_user_path(@user)%>

app/views/welcome/_foot.html.erb
<div class="bottom">
<div class="navbar navbar-expand-lg navbar-dark" style="background-color: #cc0000">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContentfoot" aria-controls="navbarSupportedContentfoot" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContentfoot" align="center">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="#">About Us<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">How To Join<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">Term & Conditions<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">Privacy Policy<span class="sr-only">(current)</span></a>
    </li>
  </ul>
</div>
</div>
</div>

app/views/welcome/_link1.html.erb
<div class="navbar navbar-expand-lg navbar-dark" style="background-color: #cc0000">
  <div class="navbar-brand" id="bor"><%= image_tag("logo.png", width:"80px")%></div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContent" align="center">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Events
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#" ><center>Upcoming</center></a>
          <a class="dropdown-item" href="#"><center>Resent</center></a>
        </div>
      </li>
    </li>
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item ">
      
     
      <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sign in/Sign up
        </a>
     <div class="dropdown-menu dropdown-menu-right">
            <div class="px-4 py-3">
              <%=form_with url: login_path do |a| %>
                Email
                <div class="form-group">
                  <%= a.text_field :email, class: 'form-control' %>
                </div>
                Password
                <div class="form-group">
                  <%= a.password_field :password, class: 'form-control'%>
                </div>
                <input type="text" data-provide='datepicker'>
                <%= date_field :date, class: 'datepicker'%>
                <%= time_field :time, class: 'timepicker'%>
                <br>
      <div class='input-append bootstrap-timepicker-component' style='display: inline;'>
  <input class='dateselect-time input-small' type='text' data-time='12:45 PM'>
  <span class='add-on'><i class='icon-time'></i></span>
</div>  
                <div class="form-group">
                  <%= submit_tag%>
                </div>
              <%end%>         
            </div>
              <div class="dropdown-divider"></div>
                <a class="dropdown-item" >New around here?<a type="button" class="btn btn-primary dropdown-item" data-toggle="modal" data-target="#exampleModalCenter">Sign up</a></a>
      </div> 
              <div class="modal fade" style="display: none; " id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%=form_for :user, url: '/users' do |f|%>
        <div align="left">Full Name</div>
        <div class="form-group">
        <%=f.text_field :name, class: 'form-control'%>
        </div>
        <div align="left">Email</div>
        <div class="form-group">
        <%=f.text_field :email, class: 'form-control'%>
        </div>
        <div align="left">Password</div> 
        <div class="form-group">
        <%=f.password_field :password, class: 'form-control'%>
        </div>
        <div align="left">Password Confirmation</div>
        <div class="form-group">
        <%=f.password_field :password_confirmation, class: 'form-control'%>
        </div>
        <div class="form-group">
        <%=f.file_field :file%>
        </div>
        <div align="right">
        <%=f.submit"Daftar"%>
        </div>
        <%end%>
      </div>
    </div>
  </div>
</div>
    </li>
  </ul>
</div>
</div>

app/views/welcome/index.html.erb
<%=render 'link1'%>

<!-- badan -->
<div class="row jarak">
<div class="col-md-12">
		<div class="card" id="jar">
			<div class="card-header" align="center" style="height: 50px"><h2 class="pro">Profil</h2></div>
				<div class="card-body bg-secondary">
					<div align="center">
					<div id="carouselExampleIndicators" class="carousel slide justify-content-center" data-ride="carousel" align="center" style="width: 80%" style="height: 100%">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src=".../800x400?auto=yes&bg=777&fg=555&text=First slide" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src=".../800x400?auto=yes&bg=666&fg=444&text=Second slide" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src=".../800x400?auto=yes&bg=555&fg=333&text=Third slide" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
	  				<div id="jar">
						<h3 align="left">Upcoming Events</h3>
						
	  						<div class="row" id="bw">
	  							<div class="col-md-6">
	  								<div class="card" id="jar">
									<div class="card-header" align="center" style="height: 50px"><h3 align="left">Judul</h3></div>
										<div class="card-body bg-secondary">
											Foto 
											Tanggal
											Pemateri
									</div>
									</div>
	  							</div>
	  							<div class="col-md-6">
	  								<div class="card" id="jar">
									<div class="card-header" align="center" style="height: 50px"><h3 align="left">Judul</h3></div>
										<div class="card-body bg-secondary">
											Foto 
											Tanggal
											Pemateri
									</div>
									</div>
	  							</div>
	  						</div>

	  					
					</div>

					<div id="jar">
						<h3 align="left">Recent Events</h3>
	  						<div class="row"  id="bw">
	  							<div class="col-md-6">
	  								<div class="card" id="jar">
									<div class="card-header" align="center" style="height: 50px"><h3 align="left">Judul</h3></div>
										<div class="card-body bg-secondary">
											Foto 
											Tanggal
											Pemateri
									</div>
									</div>
	  							</div>
	  							<div class="col-md-6">
	  								<div class="card" id="jar">
									<div class="card-header" align="center" style="height: 50px"><h3 align="left">Judul</h3></div>
										<div class="card-body bg-secondary">
											Foto 
											Tanggal
											Pemateri
									</div>
									</div>
	  							</div>
	  						</div>

					</div>

					<div id="jar">
						<h3>About Us</h3>
						KomoDev adalah sebuah komunitas yang dapat membantu para penggiat IT yang memiliki tujuan untuk membangun dan memajukan potensi IT di Nusa Tenggara Timur. Didirikan dengan nama awal Kupang Programmers Community pada tanggal 04 Agustus 2018, dan berubah nama menjadi KomoDev pada tanggal 18 Agustus 2018.
					</div>
	  			</div>
		</div>

</div>
</div>

<%=render 'foot'%>

app/views/welcome/link.html.erb
<%=form_tag '/login' do%>
            Email
            <div class="form-group">
            <%=text_field_tag :email %>
            </div>
            Password
            <div class="form-group">
            <%= password_field_tag :password%>
            </div>
            <div class="form-group">
            <%= submit_tag%>
             </div>
            <%end%>

             <%if current_user%>
      Signed in as <%= current_user.name%>|<%=link_to "Logout",'/logout'%>
      <%else%>
      <%=link_to 'Login','/login'%>|<%=link_to 'Sign Up','signup'%>
      <%end%>